landingpage/urls.py
from django.urls import path
from . import views


app_name = 'landingpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('FormLangganan',views.langganan_create_view, name= 'langganan_create'),
    path('FormLanggananBerhasil',views.langganan_berhasil, name= 'langganan_berhasil'),
    path('Berita',views.berita, name= 'berita'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from statistikCovid import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landingpage.urls"), name = "landingpage"),
    path('covidResearch/', include("covidResearch.urls"), name = "covidResearch"),
    path('dampak/', include("dampak.urls"), name = "dampak"),
    path('statistik/', include("statistikCovid.urls"), name = "statistikCovid"),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpage/models.py
from django.db import models

# Create your models here.
class Langganan(models.Model):
    namaOrang  = models.CharField(max_length = 30)
    email      = models.CharField(max_length = 30)
    noTelepon  = models.CharField(max_length = 30)

    def __str__(self):
        return self.namaOrang

landingpage/forms.py
from django import forms

from .models import Langganan

class LanggananForm(forms.ModelForm):
    namaOrang  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nama Kamu'}) , label = ' Nama = ' )
    email      = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email Kamu'}) , label = ' Alamat Email = ')
    noTelepon  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nomor Telepon Kamu'}) , label = ' No Telepon = ')
  
    class Meta:
        model = Langganan
        fields = '__all__'

landingpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .forms import LanggananForm
from .models import Langganan


# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def berita(request):
    return render(request, 'home/berita.html')

def langganan_berhasil(request):
    count= Langganan.objects.all().count()
    context= {'count': count}
    return render(request, 'home/langganan_berhasil.html',context)

def langganan_create_view(request):
    form = LanggananForm()
    if request.method == 'POST':
        form = LanggananForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/FormLanggananBerhasil')
    return render(request, 'home/langganan_create.html', {'form':form})

landingpage/templates/home/berita.html
{% extends "base_template.html" %}
    {% block content %}
    {% load static %}

<!---Berita Korona -->
<h1 style="margin-top: 40px;">Berita Hari Ini</h1>

<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

  <div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>
  
<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

<!---Jumbotron -->
<div class="jumbotron jumbotron-fluid" style="margin-top: 40px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:langganan_create' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div> 

{% endblock %}

landingpage/templates/home/index.html
{% extends "base_template.html" %}
    {% block content %}
    {% load static %}

    <div class="container-fluid padding" style="margin-top:90px; ">
        <div class="row padding">
            <div class="col-md-12 col-lg-7">
                <h1>Virus Corona</h1>
                <p>Coronavirus (CoV) adalah keluarga besar virus yang menyebabkan penyakit mulai
                    dari gejala ringan sampai berat. Ada setidaknya dua jenis coronavirus yang diketahui
                    menyebabkan penyakit yang dapat menimbulkan gejala berat seperti Middle East Respiratory Syndrome (MERS-CoV) dan Severe Acute Respiratory Syndrome (SARS-CoV). Novel coronavirus (2019-nCoV) adalah virus jenis baru yang belum pernah diidentifikasi
                    sebelumnya pada manusia. Virus corona adalah zoonosis (ditularkan antara hewan dan
                    manusia). </p>
                
            </div>
        
            <div class="col-lg-5">
          
            <img src="../../static/home/Virus.png" alt="Ini_Gambar_Virus" width="50%" style="margin-left: 20em;">
            </div>
        </div>
        </div>
     
        
<!---Jumbotron -->
<br><br>
<div class="jumbotron jumbotron-fluid" style="margin-top: 90px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:langganan_create' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div>


<!---Peta -->
<div class="card">
  <div class="card-body">
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    <h1 class="card-title">Data Penyebaran Corona</h5>
    <p class="card-text">Link Network Graph : <a href="https://app.powerbi.com/view?r=eyJrIjoiMTZhNmY2OTEtMGUxNi00NWNhLThjMzQtZTI1MjQ4NmU5ZDY2IiwidCI6IjVkNWE3MWRkLTk0ZDMtNDM0OC04YzViLWY0MDhiOTUyYjBkMSIsImMiOjEwfQ%3D%3D">Ini</a></p>
    
    <div class="row">
      <div class="col-sm-4" style="background-color: #EB5757;">
      <br>
      <h2>Kasus Meninggal</h2>
      <h3>15.037</h3>
      <br>
    </div>
      
    <div class="col-sm-4" style="background-color: #FDD262;">
      <br>
      <h2>Kasus Positif</h2>
      <h3>457.735</h3>
      <br>
    </div>


    <div class="col-sm-4" style="background-color: #0ACF83;">
      <br>
      <h2>Kasus Positif</h2>
      <h3>385.094</h3>
      <br>
    </div>
    
  </div>
  </div>
  <img class="card-img-bottom" src="../../static/home/indonesia.jpg" alt="Card image cap">



</div>

<!---Berita Korona -->

<h1 style="margin-top: 40px;">Berita Corona</h1>
<br>

<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

  <center><a href="{% url 'landingpage:berita' %}" class="btn btn-primary" style="margin-top: 40px;">Lihat Berita Lainnya</a></center>

 <!---Jumbotron -->
<div class="jumbotron jumbotron-fluid" style="margin-top: 40px; background-color: #EB5757; color: white;">
    <div class="container">
        <p class="lead" style="float: left;";><b>Ingin terus update dengan berita terbaru mengenai virus Corona</b></p>
        <a href="{% url 'landingpage:langganan_create' %}" class="btn btn-primary" style="float: right;" target="_blank">Klik untuk Berlangganan</a>
    </div>
</div> 

  <br><br><br>


{% endblock %}

landingpage/templates/home/langganan_berhasil.html
{% extends "base_template.html" %}
    {% block content %}
    {% load crispy_forms_tags %}
    {% load static %}

    <center>
    <h1>Terima kasih sudah berlangganan dengan kami</h1>
    <h2>Silakkan cek email Anda untuk konfirmasi</h2>
    <hr>
    <h1>Anda adalah orang ke - {{count}} yang berlangganan dengan kami</h1>
    </center>

    
<!---Berita Korona -->

<h1 style="margin-top: 40px;">Berita Corona</h1>
<br>

<div class="row">

    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p> 
          <hr>
          <h5 class="card-title">Harga masker kembali normal</h5>
          <p class="card-text">13 November 2020</p>
          <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>   
            <hr>
            <h5 class="card-title">83 Karyawan BJB Positif Corona, Kantor 'Lockdown'</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

    <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>
            <hr>   
            <h5 class="card-title">Pasien Covid-19 RI Hari Ini Tambah 4.173 Orang</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <img class="card-imd-top" src="../../static/home/virus-corona_200416143238-709.jpg" width="100%"><p></p>  
            <hr> 
            <h5 class="card-title">103 Kasus , Lampung Catat Lonjakan Corona Tertinggi</h5>
            <p class="card-text">13 November 2020</p>
            <a href="#"><h5 class="card-text" style="color: #EB5757; float: right;">Lihat</h5></a>
          </div>
        </div>
      </div>
  </div>

  <center><a href="{% url 'landingpage:berita' %}" class="btn btn-primary" style="margin-top: 40px;">Lihat Berita Lainnya</a></center>


{% endblock %}

landingpage/templates/home/langganan_create.html
{% extends "base_template.html" %}
    {% block content %}
    {% load crispy_forms_tags %}
    {% load static %}

    <h1>Form Langganan Berita Covid</h1>


    <div class="container-fluid padding">
        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          
          <br>
          <b>* Kami akan mengirimkan informasi-informasi terbaru melalui email Anda</b>
          <br><br>

          <button type="submit" class="btn btn-primary">Submit</button>
          <a type="button" class="btn btn-light" href="/"><b>Back</b></a>
        </form>
      </div>
    </div>
  </div>



{% endblock %}