covidResearch/urls.py
from django.urls import path
from covidResearch.views import home, uploadNews, detailNews, searchNews

app_name = "covidResearch"

urlpatterns = [
    path('', home, name="Home"),
    path('uploadNews/', uploadNews, name="Upload"),
    path('news/<int:pk>', detailNews, name="DetailNews"),
    path('search/', searchNews, name="Search")
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from statistikCovid import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landingpage.urls"), name = "landingpage"),
    path('covidResearch/', include("covidResearch.urls"), name = "covidResearch"),
    path('dampak/', include("dampak.urls"), name = "dampak"),
    path('statistik/', include("statistikCovid.urls"), name = "statistikCovid"),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covidResearch/models.py
from django.db import models

# Create your models here.

def get_upload_path(instance, filename):
    model = instance.news.pk
    return f'{model}/images/{filename}'

class News(models.Model):
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=50)
    date_published = models.DateTimeField(auto_now_add=True)
    desc = models.CharField(max_length=500)
    shortDesc = models.CharField(max_length=100)

class Image(models.Model):
    news = models.ForeignKey(News, default=None, related_name="image", on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_upload_path)
    default = models.BooleanField(default=False)

covidResearch/forms.py
from django import forms
from covidResearch.models import News, Image

class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Judul Artikel'}) , label = 'Judul' )
    author = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Penulis Artikel'}) , label = 'Penulis' )
    desc = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'placeholder': 'Isi artikel disini'}) , label = 'Isi Artikel' )
    shortDesc = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'placeholder': 'Isian singkat artikel'}) , label = 'Deskripsi Artikel' )
    class Meta:
        model = News
        fields = ('title','author','desc','shortDesc',)

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label = 'Gambar/Foto Kegiatan/Hasil Penelitian')
    class Meta:
        model = Image
        fields = ('image',)

covidResearch/views.py
from django.shortcuts import render, redirect
from django.forms import modelformset_factory
from covidResearch.forms import NewsForm, ImageForm
from covidResearch.models import News, Image
# from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

def home(request):
    allNews = News.objects.all()
    return render(request, "home.html", {'News': allNews})

def uploadNews(request):
    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=5)
    if request.method == 'POST':
        formPost = NewsForm(request.POST)
        # Using Form Set for Multiple Files
        formSet = ImageFormSet(request.POST, request.FILES, queryset=Image.objects.none())
        if formPost.is_valid() and formSet.is_valid():
            # Saved the form to render a model
            post_form = formPost.save(commit=False)
            post_form.save()
            for form in formSet.cleaned_data:
                # This helps to not crash if the user do not upload all the photos
                if form:
                    image = form['image']
                    photo = Image(news=post_form, image=image)
                    photo.save()
            return redirect("covidResearch:Home")
    else:
        form = NewsForm()
        formImageSet = ImageFormSet(queryset=Image.objects.none())
        return render(request, "upload_news.html", {'Form': form, 'ImageSet': formImageSet})

def detailNews(request, pk):
    singleNews = News.objects.get(pk = pk)
    return render(request, "detail_news.html", {'News': singleNews})


def searchNews(request):        
    if request.GET.get('search'):
        searchName =  request.GET.get('search')
        # Using Django Q method for query search. icontains for insensitive case
        allNews = Q(title__icontains=searchName) | Q(author__icontains=searchName) | Q(shortDesc__icontains=searchName)
        results = News.objects.filter(allNews).distinct()
        return render(request, "home.html", {"News": results})
    else:
        return render(request, "search_news.html")

covidResearch/templates/base_research.html
{% extends "base_template.html" %}

  {% block content%}
  <script>
    function openNav() {
      document.getElementById("sidebar").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
    }
    
    function closeNav() {
      document.getElementById("sidebar").style.width = "0";
      document.getElementById("main").style.marginLeft= "0";
    }
    </script>

  <div id="sidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'covidResearch:Home' %}">Penelitian</a>
      <a href="{% url 'covidResearch:Upload'%}">Unggah Penelitian</a>
      <a href="{% url 'covidResearch:Search'%}">Mencari Penelitian</a>
  </div>
  
  <div id="main">
    <button class="openbtn" onclick="openNav()">&#9776;Sidebar</button>
    <div class="container" style="margin-top: 20px;">
      {% block body %}
      {% endblock %}
    </div>
  </div>
  {% endblock %}

covidResearch/templates/detail_news.html
{% extends "base_research.html" %}
    {% load tz %}

<!-- News attr : newsId, title, author, date_published, desc, shortDesc, newsImg -->
    {% block title %}
    {{News.title}}
    {% endblock %}

    {% block body %}
    <div class="articles-details">
        <div class="articles-desc">
            <div class="articles-desc title">
                <div style="font-weight: bold;">
                    {{News.title}} 
                </div>
                <div>
                    {% localtime on %}
                    {{News.date_published}}
                    {% endlocaltime %}
                </div>
            </div>
            <div class="articles-desc fill">                
                <div>
                    Penulis : {{News.author}}
                </div>
                <div>
                    Deskripsi :
                    <br>
                    {{News.shortDesc}}
                </div>
            </div>
        </div>
        <div class="articles-img">
            {% if News.image.first %}
                {% for img in News.image.all %}
                <img src='{{img.image.url}}' class="img-fluid img-thumbnail">
                {% endfor%}
            {% endif %}            
        </div>       
    </div>

    {% endblock %}

covidResearch/templates/home.html
{% extends "base_research.html" %}
    {% load tz %}
    {% block title%} Penelitian {% endblock%}

    {% block body %}

    <!-- News attr : newsId, title, author, date_published, desc, shortDesc, newsImg -->
    {% if News %}
    {% for New in News%}
    <div class="articles">
        <div class="articles-img">
            <a style="color: inherit;"href= "{% url 'covidResearch:DetailNews' New.pk %}">
                {% if New.image.first %}
                <img src='{{New.image.first.image.url}}' class="img-fluid img-thumbnail"></a>
                {% endif %}            
        </div>
        <div class="articles-desc">
            <div class="articles-desc title">
                <div style="font-weight: bold;">
                    <a style="color: inherit;"href= "{% url 'covidResearch:DetailNews' New.pk %}">{{New.title}}</a>                    
                </div>
                <div>
                    {% localtime on %}
                    {{New.date_published}}
                    {% endlocaltime %}
                </div>
            </div>
            <div class="articles-desc fill">                
                <div>
                    Penulis : {{New.author}}
                </div>
                <div>
                    Deskripsi :
                    <br>
                    {{New.shortDesc}}
                </div>
            </div>
        </div>       
    </div>
    {% endfor%}
    {% endif %}
    
    {% endblock %}

covidResearch/templates/search_news.html
{% extends "base_research.html" %}
    {% block title%} Mencari Penelitian {% endblock%}

    {% block body %}
    <div class="articles" style="flex-direction: column">
        Mencari keywords dalam judul, penulis, dan deksripsi singkat
        <form id="searchForm" method="GET" action="{% url 'covidResearch:Search' %}">
            <input type="text" name="search" placeholder="Mencari Artikel" />
            <button class="btn btn-link btn-lg" type="button" style="background-color: #EB5757; color:white" onclick="searchForm.submit()">Search</button>
        </form>
    </div>

    {% endblock %}

covidResearch/templates/upload_news.html
{% extends "base_research.html" %}
    {% load crispy_forms_tags %}

    {% block body %}
    <div>
        <form action="{% url 'covidResearch:Upload' %}"method="POST" enctype="multipart/form-data"> 
            {% csrf_token %} 
            {{Form|crispy}}
            Gambar/Foto pertama akan dijadikan thumbnail
            <br>
            Max Gambar/Foto = 5
            {{ImageSet|crispy}}
            <br>
            <button type="submit">Upload</button>
        </form>
    </div>

    {% endblock %}